train:
  data_path: data/processed/processed_data.csv
  target: quality_binary
  model_name: rf
  output_dir: models
  seed: 121212

model:
  lr:
    C: 1.0
    max_iter: 1000
    penalty: l2
    class_weight: balanced
    solver: lbfgs

  rf:
    n_estimators: 1500
    max_depth: Null
    min_samples_split: 2
    random_state: 42

  mlp:
    hidden_layer_sizes: [100, 50, 10]
    activation: relu
    max_iter: 1000
    random_state: 42
