train:
  data_path: data/processed/dataset.csv
  target: quality_binary
  model_name: mlp
  output_dir: models

model:
  lr:
    C: 1.0
    max_iter: 200
    penalty: l2

  rf:
    n_estimators: 200
    max_depth: null
    min_samples_split: 2

  mlp:
    hidden_layer_sizes: [64, 32]
    activation: relu
    max_iter: 300
